//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public coupen()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public long coupen_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime starting_date { get; set; }
        public System.DateTime ending_date { get; set; }
        public double discount_rate { get; set; }
        public double minimun_purchase_price { get; set; }
        public double maximum_purchase_price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
