//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address_type> address_type { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<coupen> coupens { get; set; }
        public virtual DbSet<currency_type> currency_type { get; set; }
        public virtual DbSet<image> images { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Order_detail> Order_detail { get; set; }
        public virtual DbSet<order_return> order_return { get; set; }
        public virtual DbSet<order_status> order_status { get; set; }
        public virtual DbSet<payment_mode> payment_mode { get; set; }
        public virtual DbSet<price_decision_factor> price_decision_factor { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<product_variant_value> product_variant_value { get; set; }
        public virtual DbSet<return_reason> return_reason { get; set; }
        public virtual DbSet<return_status> return_status { get; set; }
        public virtual DbSet<review> reviews { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sub_category> sub_category { get; set; }
        public virtual DbSet<User_account> User_account { get; set; }
        public virtual DbSet<User_address> User_address { get; set; }
        public virtual DbSet<variant> variants { get; set; }
        public virtual DbSet<variant_value> variant_value { get; set; }
        public virtual DbSet<wishlist> wishlists { get; set; }
    }
}
