//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_detail
    {
        public long order_detail_id { get; set; }
        public int quantity { get; set; }
        public double total_amount { get; set; }
        public long product_variant_id { get; set; }
        public long order_id { get; set; }
        public long currency_type_id { get; set; }
    
        public virtual currency_type currency_type { get; set; }
        public virtual Order Order { get; set; }
        public virtual product_variant_value product_variant_value { get; set; }
    }
}
