//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_detail = new HashSet<Order_detail>();
            this.order_return = new HashSet<order_return>();
        }
    
        public long order_id { get; set; }
        public string order_no { get; set; }
        public System.DateTime order_date { get; set; }
        public Nullable<System.DateTime> shipdate { get; set; }
        public long status_id { get; set; }
        public long billing_add { get; set; }
        public long shipping_add { get; set; }
        public long user_id { get; set; }
        public long payment_mode_id { get; set; }
        public Nullable<long> coupen_id { get; set; }
        public double shiprate { get; set; }
    
        public virtual coupen coupen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_detail> Order_detail { get; set; }
        public virtual order_status order_status { get; set; }
        public virtual payment_mode payment_mode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_return> order_return { get; set; }
        public virtual User_account User_account { get; set; }
        public virtual User_address User_address { get; set; }
        public virtual User_address User_address1 { get; set; }
    }
}
