//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.product_variant_value = new HashSet<product_variant_value>();
            this.reviews = new HashSet<review>();
        }
    
        public long product_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public double rating { get; set; }
        public int no_users_rated { get; set; }
        public int Isactive { get; set; }
        public long price_factor_id { get; set; }
        public long category_id { get; set; }
        public long sub_category_id { get; set; }
        public long admin_id { get; set; }
        public double shipping_rate { get; set; }
        public string sku { get; set; }
        public int isvariant { get; set; }
    
        public virtual category category { get; set; }
        public virtual price_decision_factor price_decision_factor { get; set; }
        public virtual sub_category sub_category { get; set; }
        public virtual User_account User_account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_variant_value> product_variant_value { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<review> reviews { get; set; }
    }
}
