//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_variant_value
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product_variant_value()
        {
            this.carts = new HashSet<cart>();
            this.images = new HashSet<image>();
            this.Order_detail = new HashSet<Order_detail>();
            this.wishlists = new HashSet<wishlist>();
        }
    
        public long product_variant_id { get; set; }
        public string product_variant_title { get; set; }
        public long product_id { get; set; }
        public Nullable<long> variant_value_id { get; set; }
        public double MRP { get; set; }
        public double Selling_price { get; set; }
        public double discount { get; set; }
        public int discount_min_quantity { get; set; }
        public int discount_max_quantity { get; set; }
        public int weight { get; set; }
        public int unit_in_stock { get; set; }
        public int max_purchase_quantity { get; set; }
        public int quantity_per_unit { get; set; }
        public string sku { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<image> images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_detail> Order_detail { get; set; }
        public virtual product product { get; set; }
        public virtual variant_value variant_value { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wishlist> wishlists { get; set; }
    }
}
